import type { Metadata } from "next";
import Link from "next/link";
import { Sparkles } from "lucide-react";
import { ShowcaseGalleryClient } from "./showcase-gallery-client";
import { getRequestLocale } from "@/lib/server-locale";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getRequestLocale();
  if (locale === "en") {
    return {
      title: "Showcase | Postaty",
      description: "Explore real design examples generated by Postaty users with AI",
    };
  }

  return {
    title: "أعمالنا | Postaty",
    description: "شاهد نماذج من التصاميم الاحترافية التي أنشأها مستخدمو Postaty بالذكاء الاصطناعي",
  };
}

export default async function ShowcasePage() {
  const locale = await getRequestLocale();
  const t = (ar: string, en: string) => (locale === "ar" ? ar : en);

  return (
    <div className="min-h-screen">
      <section className="pt-32 pb-16 px-4 text-center relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-accent/8 rounded-full blur-[120px]" />
        </div>
        <div className="max-w-3xl mx-auto relative">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-semibold mb-6">
            <Sparkles size={16} />
            {t("أعمالنا", "Our showcase")}
          </div>
          <h1 className="text-4xl md:text-6xl font-black mb-6 leading-tight">
            {t("تصاميم حقيقية", "Real designs")}
            <br />
            <span className="text-gradient">{t("من مستخدمين حقيقيين", "from real users")}</span>
          </h1>
          <p className="text-muted text-lg md:text-xl max-w-2xl mx-auto leading-relaxed">
            {t("كل هذه التصاميم تم إنشاؤها بواسطة Postaty في ثوانٍ معدودة. تخيّل شكل إعلانك القادم.", "All these designs were generated with Postaty in seconds. Imagine what your next ad could look like.")}
          </p>
        </div>
      </section>

      <ShowcaseGalleryClient />

      <section className="py-20 px-4 text-center">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-black mb-6">{t("تبي تصميمك يكون هنا؟", "Want your design to be featured here?")}</h2>
          <p className="text-muted text-lg mb-8">{t("ابدأ الآن وصمم أول بوستر لك مجاناً.", "Start now and create your first poster for free.")}</p>
          <Link
            href="/create"
            className="inline-block px-10 py-4 bg-gradient-to-r from-primary to-primary-hover text-primary-foreground rounded-2xl font-bold text-lg shadow-xl shadow-primary/25 hover:shadow-primary/40 transition-all"
          >
            {t("صمم بوسترك الآن", "Create your poster now")}
          </Link>
        </div>
      </section>
    </div>
  );
}
